{
 "title": "Pizza Service Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(Revenue_total{source=\"jwt-pizza-service-dev\", metricName=\"Revenue\"}[1m])",
     "legendFormat": "{{metricName}}"
    }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(PizzasSold_total{source=\"jwt-pizza-service-dev\", metricName=\"PizzasSold\"}[1m])",
     "legendFormat": "{{metricName}}"
    },
    {
     "expr": "rate(CreationFailures_total{source=\"jwt-pizza-service-dev\", metricName=\"CreationFailures\"}[1m])",
     "legendFormat": "{{metricName}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "PizzaLatency_milliseconds", "legendFormat": "{{metricName}}" },
    { "expr": "EndpointLatency_milliseconds", "legendFormat": "{{metricName}}" }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(Total_total{source=\"jwt-pizza-service-dev\", metricName=\"Total\"}[30s])",
     "legendFormat": "{{metricName}}"
    },
    {
     "expr": "rate(GET_total{source=\"jwt-pizza-service-dev\", metricName=\"GET\"}[30s])",
     "legendFormat": "{{metricName}}"
    },
    {
     "expr": "rate(POST_total{source=\"jwt-pizza-service-dev\", metricName=\"POST\"}[30s])",
     "legendFormat": "{{metricName}}"
    },
    {
     "expr": "rate(PUT_total{source=\"jwt-pizza-service-dev\", metricName=\"PUT\"}[30s])",
     "legendFormat": "{{metricName}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Memory_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "CPU_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Auth Attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(Success_total{source=\"jwt-pizza-service-dev\", metricName=\"Success\"}[10m])",
     "legendFormat": "{{metricName}}"
    },
    {
     "expr": "rate(Fail_total{source=\"jwt-pizza-service-dev\", metricName=\"Fail\"}[10m])",
     "legendFormat": "{{metricName}}"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "ActiveUsers_total{source=\"jwt-pizza-service-dev\", metricName=\"ActiveUsers\"}",
     "legendFormat": "{{metricName}}"
    }
   ]
  }
 ]
}